from app.services.auth.auth_service import AuthService
from app.services.catalog.catalog_service import CatalogService
from app.services.sales.sales_service import SalesService
from app.services.inventory.inventory_service import InventoryService
from app.services.crm.crm_service import CRMService
from app.services.finance.finance_service import FinanceService
from app.services.procurement.procurement_service import ProcurementService
from app.services.marketing.marketing_service import MarketingService
from app.services.analytics.analytics_service import AnalyticsService
