from app.repositories.base_repository import BaseRepository
from app.repositories.auth.user_repository import UserRepository
from app.repositories.catalog.catalog_repository import CatalogRepository
from app.repositories.sales.sales_repository import SalesRepository
from app.repositories.inventory.inventory_repository import InventoryRepository
from app.repositories.crm.crm_repository import CRMRepository
from app.repositories.procurement.procurement_repository import ProcurementRepository
